#!/bin/bash -l
# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is provided to you under the terms of
# the GNU LGPL. Please see LICENSE in the top level directory for full
# details.
# 
#$$ -S /bin/bash

#$$ -l h_rt=$wall_time

#$$ -l mem=$memory

#$$ -N $job_name

#$$ -pe openmpi $cores_reserved

#$$ -P $project

#$$ -wd $job_results
$node_type_restriction
export TMP=$job_results
