#!/bin/bash
# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is provided to you under the terms of
# the GNU LGPL. Please see LICENSE in the top level directory for full
# details.
# 
#$$ -wd $job_results
#$$ -q all.q
#$$ -pe openmpi $cores_reserved
#$$ -N $job_name
#$$ -e $job_results/${name}.error
#$$ -o $job_results/${name}.output
