#!/usr/bin/env python
# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is provided to you under the terms of
# the GNU LGPL. Please see LICENSE in the top level directory for full
# details.
# 

import argparse
p = argparse.ArgumentParser(description='Upgrade an saved profile from "config" to "geometry"')
p.add_argument('input')
p.add_argument('output')
args = p.parse_args()

from HemeLbSetupTool.Util.ProfileUpdateTools import Upgrade
Upgrade(args.input, args.output)
