# 
# Copyright (C) University College London, 2007-2012, all rights reserved.
# 
# This file is part of HemeLB and is provided to you under the terms of
# the GNU LGPL. Please see LICENSE in the top level directory for full
# details.
# 

# Copy this file as config.yml, and specify your configuration details
results_path: "~/devel/ccs/fabric/hemelb/results"
reports_path: "~/devel/ccs/fabric/hemelb/reports"